[dependencies]

[package]
cjc-version = "0.54.3"
compile-option = ""
description = "nothing here"
link-option = ""
name = "compare_versions"
output-type = "executable"
src-dir = ""
target-dir = ""
version = "0.1.0"
package-configuration = {}
